### ISSUE TITLE
Implement AFK-Kicking System when server is full and someone tries to connect

### ISSUE THREAD

**Issue by Freezgam03** [civilgamers/SCP_Public_Development#171]
https://www.civilgamers.com/community/threads/rareys-afk-kick-time-suggestion.5084/

Essentially, this would only work when the server is full, and someone tries to connect, it would send a request and check for AFKs. People that have been AFK for a long time (maybe 1 hour) would then get kicked.

**Comment by cloakical** [comment]
No longer needed due to priority join system
