### ISSUE TITLE
1x Scopes on the RPK16 are misaligned

### ISSUE THREAD

**Issue by Freezgam03** [civilgamers/SCP_Public_Development#19]
Title of the Bug
1x scopes on the rpk16 are misaligned (at least the ones i tested on)

Evidence
https://medal.tv/games/garrys-mod/clips/hTAeLZtGk-Vku/d1337B5VoBI6?invite=cr-MSxSQU8sMzI5NTc1MTAs

(crosshair is the center of the screen and thats where the bullets are always going)

**Comment by 0-Marco** [comment]
This is because it would look highly goofy if it were aligned without a scope.
https://gyazo.com/c1970f47891bbe9180d902576afbc391

I have aligned the x1 scope on the RPK16.
