### ISSUE TITLE
SCP-173 is able to teleport to people who have no active character

### ISSUE THREAD

**Issue by CheddarSniffer** [civilgamers/SCP_Public_Development#53]

**Comment by ventz-lgtm** [comment]
I have added a new system to determine whether SCPs should ignore people with this fix. That meant we need to fix every SCP, all their sweps or abilities and make sure they CANNOT interact with:

- Other SCPs
- Players in the character select screen
- AODs
- 
We need to double check all the SCPs still also work as intended
