### ISSUE TITLE
Staff tags in OOC chat

### ISSUE THREAD

**Issue by Freezgam03** [civilgamers/SCP_Public_Development#70]
https://www.civilgamers.com/community/threads/suggestion-mod-tag-next-to-name.4062/

Make it so Staff have a tag next to their when typing in OOC chat, though it should not show anywhere else, e.g. In charactar chat

**Comment by cloakical** [comment]
Going to close this ticket, if this were ever to be implemented it would be as part of a chat overhaul, it's come up in conversation from time to time but it won't be getting done as a stand-alone thing
