### ISSUE TITLE
Garage Door unable to be repaired

### ISSUE THREAD

**Issue by Freezgam03** [civilgamers/SCP_Public_Development#71]
https://medal.tv/games/garrys-mod/clips/nSJkQT1BhRwjc/d1337W8j0g2E?invite=cr-MSxsQWYsODk0MDQzNiw

**Comment by Freezgam03** [comment]
Marked as high because it seems like a easy fix

**Comment by ventz-lgtm** [comment]
We need to test that the repair distance for all doors is still appropriate
